# Placeholder configuration while waiting for actual API keys
[general]
DATA_GOV_API_KEY = ""
DATA_GOV_RESOURCE_ID = ""
WEATHER_API_KEY = ""
NEWS_API_KEY = ""

# API Keys
openweather_api_key = "YOUR_OPENWEATHER_API_KEY"
news_api_key = "YOUR_NEWS_API_KEY"

# API URLs
[api_urls]
weather = "https://api.openweathermap.org/data/2.5"
news = "https://newsapi.org/v2"
market = "https://api.market-data.com/v1"

# Application Settings
[app]
debug = false
environment = "production"
cache_timeout = 3600
log_level = "INFO"

# Weather Settings
[weather]
default_city = "Manila"
units = "metric"
update_interval = 1800  # 30 minutes

# News Settings
[news]
default_query = "poultry farming"
max_articles = 10
cache_duration = 3600  # 1 hour

# Market Data Configuration
[market_data]
update_frequency = "daily"
data_retention_days = 30

# Dummy Market Data (for testing)
[[market_data.commodities]]
name = "Chicken Feed"
price = 25.50
unit = "kg"
trend = "stable"

[[market_data.commodities]]
name = "Day-Old Chicks"
price = 45.00
unit = "piece"
trend = "up"

[[market_data.commodities]]
name = "Eggs"
price = 6.75
unit = "piece"
trend = "down"

# Market Data Configuration
[market_data]
use_dummy_data = true
update_interval = 1800  # 30 minutes

[market_data.commodities]
corn = 7.25
soybean = 14.50
wheat = 6.75
fishmeal = 1650.00

[market_data.poultry]
broiler = 2.85
layer = 3.25
day_old_chick = 1.50
eggs = 2.25

[market_data.trends]
feed_cost_trend = "increasing"
broiler_price_trend = "stable"
egg_price_trend = "increasing"
market_sentiment = "positive"

[market_data.prices]
[[market_data.prices.items]]
type = "Broiler"
price = 125.00
unit = "per kg"
trend = "up"

[[market_data.prices.items]]
type = "Layer"
price = 95.50
unit = "per kg"
trend = "stable"

[[market_data.prices.items]]
type = "Eggs"
price = 6.25
unit = "per piece"
trend = "up"

[market_data.analysis]
[[market_data.analysis.trends]]
metric = "Demand"
value = "High"
forecast = "Increasing"

[[market_data.analysis.trends]]
metric = "Supply"
value = "Moderate"
forecast = "Stable"

[[market_data.analysis.trends]]
metric = "Price Trend"
value = "Upward"
forecast = "Rising"

# Collaboration Settings
[collaboration]
enable_chat = true
enable_posts = true
enable_connections = true
max_post_length = 1000
max_connections = 500
