# Placeholder configuration while waiting for actual API keys
[general]
DATA_GOV_API_KEY = ""
DATA_GOV_RESOURCE_ID = ""
WEATHER_API_KEY = ""
NEWS_API_KEY = ""

# API Keys
openweather_api_key = "5493ef67f4938e4266fd9a491ded941b"
news_api_key = "6d14ebf42a7b40668b6aca4daf308632"

# API URLs
[api_urls]
weather = "https://api.openweathermap.org/data/2.5"
news = "https://newsapi.org/v2"
market = "https://api.market-data.com/v1"

# Application Settings
[settings]
debug = true
environment = "production"
cache_timeout = 300
log_level = "INFO"

# Dummy Market Data Configuration
[dummy_market_data]
use_dummy_data = true

[dummy_market_data.commodities]
corn = 7.25
soybean = 14.50
wheat = 6.75
fishmeal = 1650.00

[dummy_market_data.poultry]
broiler = 2.85
layer = 3.25
day_old_chick = 1.50
eggs = 2.25

[dummy_market_data.trends]
feed_cost_trend = "increasing"
broiler_price_trend = "stable"
egg_price_trend = "increasing"
market_sentiment = "positive"

poultry_prices = [
    { type = "Broiler", price = 125.00, unit = "per kg", trend = "up" },
    { type = "Layer", price = 95.50, unit = "per kg", trend = "stable" },
    { type = "Eggs", price = 6.25, unit = "per piece", trend = "up" }
]

market_trends = [
    { metric = "Demand", value = "High", forecast = "Increasing" },
    { metric = "Supply", value = "Moderate", forecast = "Stable" },
    { metric = "Price Trend", value = "Upward", forecast = "Rising" }
]

[collaboration]
enable_chat = true
enable_posts = true
enable_connections = true
max_post_length = 1000
max_connections = 500
