# Placeholder configuration while waiting for actual API keys
[general]
DATA_GOV_API_KEY = ""
DATA_GOV_RESOURCE_ID = ""
WEATHER_API_KEY = ""
NEWS_API_KEY = ""

# API Keys
openweather_api_key = "5493ef67f4938e4266fd9a491ded941b"
news_api_key = "6d14ebf42a7b40668b6aca4daf308632"
commodities_api_key = "your_market_api_key_here"
agriculture_data_api_key = "your_agriculture_api_key"
disease_tracking_api_key = "your_disease_api_key_here"

# Database Configuration
[database]
host = "localhost"
port = 5432
name = "poultry_db"
user = "admin"
password = "your_secure_password"

# API URLs
[api_urls]
weather = "https://api.openweathermap.org/data/2.5"
news = "https://newsapi.org/v2"
market = "dummy"  # Using dummy data instead of real API
disease = "https://api.disease-tracking-provider.com/v1"
financial = "https://api.example.com/financial"

# Application Settings
[settings]
debug = false
environment = "production"
cache_timeout = 3600
log_level = "INFO"

# Security
[security]
secret_key = "your_production_secret_key"
jwt_secret = "your_production_jwt_secret"

# Dummy Financial/Market Data (for development)
[market_data]
use_dummy_data = true
dummy_data_refresh_interval = 300  # seconds

# Dummy Market Data Configuration
[dummy_market_data]
commodities = [
    { name = "Chicken Feed", price = 450.00, unit = "per ton", trend = "up" },
    { name = "Corn", price = 180.50, unit = "per quintal", trend = "stable" },
    { name = "Soybean Meal", price = 520.75, unit = "per ton", trend = "down" },
    { name = "Wheat Bran", price = 220.25, unit = "per quintal", trend = "up" }
]

poultry_prices = [
    { type = "Broiler", price = 125.00, unit = "per kg", trend = "up" },
    { type = "Layer", price = 95.50, unit = "per kg", trend = "stable" },
    { type = "Eggs", price = 6.25, unit = "per piece", trend = "up" }
]

market_trends = [
    { metric = "Demand", value = "High", forecast = "Increasing" },
    { metric = "Supply", value = "Moderate", forecast = "Stable" },
    { metric = "Price Trend", value = "Upward", forecast = "Rising" }
]
